### ISSUE TITLE
Various Suggestions

### ISSUE THREAD

**Issue by Drc-DEV** [ryandw11/UltraBar#1]
Add a configurable World Whitelist in the BossBarMessages, which makes you show the bossbar timed messages only in the worlds the user wants.
Add a configurable option to randomize the order of the messages shown, instead of only having the choice of broadcasting them in order.
Add a command to show the list of the bossbarmessages in-game and a way to add/delete/edit them in-game.
Make the duration of each BossBarMessage configurable. Make it so the duration of each message must be less than the time between messages, so that they won't overlap, just as a precaution.
Expose the BossBarMessages section in a different configuration file (example: BossBarMessages.yml) as it is misleadingly put under the "OnJoin" section, which could be rather confusing to some people.
Add PlaceholderAPI compatibility in order to show PlaceholderAPI variables in the messages (could be really useful to some).

**Comment by ryandw11** [comment]
Quite a few of these will require some recoding of the plugin but I will look into it. Thanks for the suggestions.

**Comment by ryandw11** [comment]
All of them except the managing boss bar messages in-game will be implemented. Adding and deleting them are already features. This update will be for 1.13 for right now. I may release a 1.9-1.12 version of this too also.

**Comment by ryandw11** [comment]
Released in UltraBar version 1.5.0. This version supports 1.11 - 1.13.

**Comment by Drc-DEV** [comment]
Thanks
