### ISSUE TITLE
How do I show a player name in the boss bar?

### ISSUE THREAD

**Issue by Dragons788** [ryandw11/UltraBar#23]
Heyo I use the UltraBar plugin and in the message I want it to say "Welcome {player}" but it doesnt say the players name it just says "{player}" and I dont know how to fix this

**Comment by ryandw11** [comment]
Is this when the player first joins? Can I see your config?

**Comment by Dragons788** [comment]
It is not when the player first joins. Its one of the messages that repeats.
Here is the part where its not working (Its the first message)

BossBarMessages:
  Enabled: true
  World_Whitelist_Enabled: false
  Random_Order: false
  World_Whitelist:
  - world
  Number_Of_Messages: 2
  '1':
    Message: '&6&lWelcome &e&l{player}'
    Color: green
    Style: '0'
    Time: 5
  '2':
    Message: '&e&lLumberSim.minehut.gg'
    Color: green
    Style: '0'
    Time: 10

**Comment by ryandw11** [comment]
You can't do that currently. The reason why is that all players on the server see the exact same bar.

**Comment by Dragons788** [comment]
So, how would I get it to show a personal message with there name?
