### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Tomigames** [ryandw11/UltraBar#24]
How do I make so that an announcements goes and then there is a 10minute pause then anotherone goes by. Am I soposed to use the BossBarMessages function?

**Comment by ryandw11** [comment]
There isn't one right now. You can only have them swap after x amount of time.

(If you are talking about the programming api, then that is different.)

**Comment by Tomigames** [comment]
There is this server which I play at that uses your plugin and sends a bossbar announcement and then there is a 10minute pause and then once again another announcemnt. But okey :c

**Comment by Tomigames** [comment]
Is there plans to add this feature in the future? If so how far away is it from the realease date?
