### ISSUE TITLE
UltraChat build into UltraBar?

### ISSUE THREAD

**Issue by OmikronOverload** [ryandw11/UltraBar#26]
Hello, 
I love UltraBar but since the newest version there is UltraChat built into it and i cant find a way to not use it.
I mean its cool and all but i am using Essentials-Chat.
I does have Essentials support but doesnt use the prefixes, player-names and world-prefixes in Essentials.

Its cool and all but could you add a way to not use UltraChat?

Thx 
OmikronOverload

**Comment by ryandw11** [comment]
UltraChat is not meant to come with UltraBar and it must be a compile error. I will fix this issue immediately.

**Comment by ryandw11** [comment]
The latest version (2.2), which I downloaded from Spigot, does not contain any code related to UltraChat. Did you install UltraChat by accident?

**Comment by OmikronOverload** [comment]
Hey,
I am using AutoPlug to auto-update any Plugin.
It seems like AutoPlug Downloaded Ultrachat instead of Ultrabar and Named it Ultrabar. Which is really strange.
The Developer of AutoPlug already knows about this Bug ^^.
I was confused by this, theres actually nothing wrong within Ultrabar. 
Server Owner Problems.
