### ISSUE TITLE
Whitelist filter not working properly

### ISSUE THREAD

**Issue by markusew** [ryandw11/UltraBar#27]
Under the "BossBarMessages" setting in the config I have
```  
World_Whitelist:
  - Resource
  - world_nether
```
Despite it specifying world_nether, the regular world "world" also gets the messages. I believe that it's cause it doesnt' check if the whole world name is the same, and just that the whitelisted worlds contains that string.

This was tested on tuinity 1.16.1

**Comment by ryandw11** [comment]
Does it display in any other world that it isn't suppose to or is it just the 'world' world?

**Comment by markusew** [comment]
It only displays it in the "world" and "world_nether". It does however flicker a bit in "world" and that doesnt happen in "world_nether"

**Comment by ryandw11** [comment]
Fixed in 2.2.1. Thanks for reporting this bug.
