### ISSUE TITLE
Bar timer goes negative before removing itself.

### ISSUE THREAD

**Issue by mibby** [ryandw11/UltraBar#30]
UltraBar 2.2.4

``/bar player:mibby msg:"&f&lServer restart in: &b&l%time_left%" color:blue time:60 style:0``

When you send a bar to a player or to everyone, the timer ticks down and displays ``-1`` at the end before it is removed. Is there any way to not overflow into negative and remove itself when it hits 0?

**Comment by ryandw11** [comment]
Currently the plugin does not remove a bar until it hits a negative number. [BossBarTimer.java#L30](https://github.com/ryandw11/UltraBar/blob/master/src/main/java/me/ryandw11/ultrabar/BossBarTimer.java#L30)]

I can fix this in the next update by just simply have it not display any numbers less than 0.

**Comment by mibby** [comment]
Much appreciated, thanks.
